development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: norovirus_development
  username: root
  password: d3pl0y
  socket: /tmp/mysql.sock
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: norovirus_test
  username: root
  password:
  socket: /tmp/mysql.sock
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: norovirus_production
  username: root
  password: d3pl0y
  socket: /var/run/mysqld/mysqld.sock